// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.0
// source: test.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 踢出类型
type KickType int32

const (
	KickType_Unknow       KickType = 0 // Kick
	KickType_Squeeze      KickType = 1 // 挤号
	KickType_GameNotFound KickType = 2 // 游戏服
)

// Enum value maps for KickType.
var (
	KickType_name = map[int32]string{
		0: "Unknow",
		1: "Squeeze",
		2: "GameNotFound",
	}
	KickType_value = map[string]int32{
		"Unknow":       0,
		"Squeeze":      1,
		"GameNotFound": 2,
	}
)

func (x KickType) Enum() *KickType {
	p := new(KickType)
	*p = x
	return p
}

func (x KickType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KickType) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (KickType) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x KickType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KickType.Descriptor instead.
func (KickType) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

// 登录
type ReqGateLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	From     int32  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	GateId   uint32 `protobuf:"varint,3,opt,name=gateId,proto3" json:"gateId,omitempty"`
}

func (x *ReqGateLogin) Reset() {
	*x = ReqGateLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGateLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGateLogin) ProtoMessage() {}

func (x *ReqGateLogin) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGateLogin.ProtoReflect.Descriptor instead.
func (*ReqGateLogin) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *ReqGateLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReqGateLogin) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ReqGateLogin) GetGateId() uint32 {
	if x != nil {
		return x.GateId
	}
	return 0
}

// 登录成功
type ResGateLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	GameId uint32 `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	RoomId uint32 `protobuf:"varint,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	HallId uint32 `protobuf:"varint,4,opt,name=hallId,proto3" json:"hallId,omitempty"`
}

func (x *ResGateLogin) Reset() {
	*x = ResGateLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResGateLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGateLogin) ProtoMessage() {}

func (x *ResGateLogin) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGateLogin.ProtoReflect.Descriptor instead.
func (*ResGateLogin) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *ResGateLogin) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *ResGateLogin) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *ResGateLogin) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ResGateLogin) GetHallId() uint32 {
	if x != nil {
		return x.HallId
	}
	return 0
}

// 离开
type ReqGateLeave struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGateLeave) Reset() {
	*x = ReqGateLeave{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGateLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGateLeave) ProtoMessage() {}

func (x *ReqGateLeave) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGateLeave.ProtoReflect.Descriptor instead.
func (*ReqGateLeave) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

// 踢人
type GateKick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type KickType `protobuf:"varint,1,opt,name=type,proto3,enum=KickType" json:"type,omitempty"`
}

func (x *GateKick) Reset() {
	*x = GateKick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateKick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateKick) ProtoMessage() {}

func (x *GateKick) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateKick.ProtoReflect.Descriptor instead.
func (*GateKick) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *GateKick) GetType() KickType {
	if x != nil {
		return x.Type
	}
	return KickType_Unknow
}

// 心跳
type HeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerType uint32 `protobuf:"varint,1,opt,name=serverType,proto3" json:"serverType,omitempty"`
	ServerId   uint32 `protobuf:"varint,2,opt,name=serverId,proto3" json:"serverId,omitempty"`
}

func (x *HeartBeat) Reset() {
	*x = HeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeat) ProtoMessage() {}

func (x *HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeat.ProtoReflect.Descriptor instead.
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *HeartBeat) GetServerType() uint32 {
	if x != nil {
		return x.ServerType
	}
	return 0
}

func (x *HeartBeat) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

// 注册
type Regist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerType uint32 `protobuf:"varint,1,opt,name=serverType,proto3" json:"serverType,omitempty"`
	ServerId   uint32 `protobuf:"varint,2,opt,name=serverId,proto3" json:"serverId,omitempty"`
}

func (x *Regist) Reset() {
	*x = Regist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Regist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Regist) ProtoMessage() {}

func (x *Regist) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Regist.ProtoReflect.Descriptor instead.
func (*Regist) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *Regist) GetServerType() uint32 {
	if x != nil {
		return x.ServerType
	}
	return 0
}

func (x *Regist) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

// 推送
type GatePushMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GatePushMsg) Reset() {
	*x = GatePushMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatePushMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatePushMsg) ProtoMessage() {}

func (x *GatePushMsg) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatePushMsg.ProtoReflect.Descriptor instead.
func (*GatePushMsg) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (x *GatePushMsg) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// 请求房间列表
type ReqRoomList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqRoomList) Reset() {
	*x = ReqRoomList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqRoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRoomList) ProtoMessage() {}

func (x *ReqRoomList) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRoomList.ProtoReflect.Descriptor instead.
func (*ReqRoomList) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

// 房间信息
type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint32 `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	RoomId   uint32 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Tag      int32  `protobuf:"varint,3,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *RoomInfo) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *RoomInfo) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomInfo) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

// 答复房间列表
type ResRoomList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*RoomInfo `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *ResRoomList) Reset() {
	*x = ResRoomList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResRoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResRoomList) ProtoMessage() {}

func (x *ResRoomList) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResRoomList.ProtoReflect.Descriptor instead.
func (*ResRoomList) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{9}
}

func (x *ResRoomList) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// 请求进入房间
type ReqEnterRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TempleteId uint32 `protobuf:"varint,1,opt,name=templeteId,proto3" json:"templeteId,omitempty"`
}

func (x *ReqEnterRoom) Reset() {
	*x = ReqEnterRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqEnterRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqEnterRoom) ProtoMessage() {}

func (x *ReqEnterRoom) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqEnterRoom.ProtoReflect.Descriptor instead.
func (*ReqEnterRoom) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{10}
}

func (x *ReqEnterRoom) GetTempleteId() uint32 {
	if x != nil {
		return x.TempleteId
	}
	return 0
}

// 进房答复
type ResEnterRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids []uint32 `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
}

func (x *ResEnterRoom) Reset() {
	*x = ResEnterRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResEnterRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResEnterRoom) ProtoMessage() {}

func (x *ResEnterRoom) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResEnterRoom.ProtoReflect.Descriptor instead.
func (*ResEnterRoom) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{11}
}

func (x *ResEnterRoom) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

// 进入老虎机
type ReqEnterSlots struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotsId int32 `protobuf:"varint,1,opt,name=slotsId,proto3" json:"slotsId,omitempty"`
}

func (x *ReqEnterSlots) Reset() {
	*x = ReqEnterSlots{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqEnterSlots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqEnterSlots) ProtoMessage() {}

func (x *ReqEnterSlots) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqEnterSlots.ProtoReflect.Descriptor instead.
func (*ReqEnterSlots) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{12}
}

func (x *ReqEnterSlots) GetSlotsId() int32 {
	if x != nil {
		return x.SlotsId
	}
	return 0
}

type SlotsElem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElemId   int32  `protobuf:"varint,1,opt,name=elem_id,json=elemId,proto3" json:"elem_id,omitempty"`      // 元素id
	ElemName string `protobuf:"bytes,2,opt,name=elem_name,json=elemName,proto3" json:"elem_name,omitempty"` // 元素名称
	Multi3   int32  `protobuf:"varint,3,opt,name=multi3,proto3" json:"multi3,omitempty"`                    // 3个元素倍数
	Multi4   int32  `protobuf:"varint,4,opt,name=multi4,proto3" json:"multi4,omitempty"`                    // 4个元素倍数
	Multi5   int32  `protobuf:"varint,5,opt,name=multi5,proto3" json:"multi5,omitempty"`                    // 5个元素倍数
}

func (x *SlotsElem) Reset() {
	*x = SlotsElem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotsElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsElem) ProtoMessage() {}

func (x *SlotsElem) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsElem.ProtoReflect.Descriptor instead.
func (*SlotsElem) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{13}
}

func (x *SlotsElem) GetElemId() int32 {
	if x != nil {
		return x.ElemId
	}
	return 0
}

func (x *SlotsElem) GetElemName() string {
	if x != nil {
		return x.ElemName
	}
	return ""
}

func (x *SlotsElem) GetMulti3() int32 {
	if x != nil {
		return x.Multi3
	}
	return 0
}

func (x *SlotsElem) GetMulti4() int32 {
	if x != nil {
		return x.Multi4
	}
	return 0
}

func (x *SlotsElem) GetMulti5() int32 {
	if x != nil {
		return x.Multi5
	}
	return 0
}

type SlotsLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LineId  int32   `protobuf:"varint,1,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	LinePos []int32 `protobuf:"varint,2,rep,packed,name=line_pos,json=linePos,proto3" json:"line_pos,omitempty"`
}

func (x *SlotsLine) Reset() {
	*x = SlotsLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotsLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsLine) ProtoMessage() {}

func (x *SlotsLine) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsLine.ProtoReflect.Descriptor instead.
func (*SlotsLine) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{14}
}

func (x *SlotsLine) GetLineId() int32 {
	if x != nil {
		return x.LineId
	}
	return 0
}

func (x *SlotsLine) GetLinePos() []int32 {
	if x != nil {
		return x.LinePos
	}
	return nil
}

type ResEnterSlots struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int32        `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	Elems  []*SlotsElem `protobuf:"bytes,2,rep,name=elems,proto3" json:"elems,omitempty"`         // 元素
	Bet    []int32      `protobuf:"varint,3,rep,packed,name=bet,proto3" json:"bet,omitempty"`     // 下注额
	Level  []int32      `protobuf:"varint,4,rep,packed,name=level,proto3" json:"level,omitempty"` // 下注等级
	Line   []int32      `protobuf:"varint,5,rep,packed,name=line,proto3" json:"line,omitempty"`   // 下注线
	Lines  []*SlotsLine `protobuf:"bytes,6,rep,name=lines,proto3" json:"lines,omitempty"`         // 中奖线路
}

func (x *ResEnterSlots) Reset() {
	*x = ResEnterSlots{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResEnterSlots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResEnterSlots) ProtoMessage() {}

func (x *ResEnterSlots) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResEnterSlots.ProtoReflect.Descriptor instead.
func (*ResEnterSlots) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{15}
}

func (x *ResEnterSlots) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *ResEnterSlots) GetElems() []*SlotsElem {
	if x != nil {
		return x.Elems
	}
	return nil
}

func (x *ResEnterSlots) GetBet() []int32 {
	if x != nil {
		return x.Bet
	}
	return nil
}

func (x *ResEnterSlots) GetLevel() []int32 {
	if x != nil {
		return x.Level
	}
	return nil
}

func (x *ResEnterSlots) GetLine() []int32 {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *ResEnterSlots) GetLines() []*SlotsLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

// 离开老虎机
type ReqLeaveSlots struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotsId int32 `protobuf:"varint,1,opt,name=slotsId,proto3" json:"slotsId,omitempty"`
}

func (x *ReqLeaveSlots) Reset() {
	*x = ReqLeaveSlots{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLeaveSlots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLeaveSlots) ProtoMessage() {}

func (x *ReqLeaveSlots) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLeaveSlots.ProtoReflect.Descriptor instead.
func (*ReqLeaveSlots) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{16}
}

func (x *ReqLeaveSlots) GetSlotsId() int32 {
	if x != nil {
		return x.SlotsId
	}
	return 0
}

// 老虎机摇奖
type ReqSlotsSpin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GameId int32 `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Bet    int32 `protobuf:"varint,3,opt,name=bet,proto3" json:"bet,omitempty"`     // 下注
	Level  int32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"` // 级别
	Lines  int32 `protobuf:"varint,5,opt,name=lines,proto3" json:"lines,omitempty"` // 线数
}

func (x *ReqSlotsSpin) Reset() {
	*x = ReqSlotsSpin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSlotsSpin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSlotsSpin) ProtoMessage() {}

func (x *ReqSlotsSpin) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSlotsSpin.ProtoReflect.Descriptor instead.
func (*ReqSlotsSpin) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{17}
}

func (x *ReqSlotsSpin) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqSlotsSpin) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *ReqSlotsSpin) GetBet() int32 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *ReqSlotsSpin) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ReqSlotsSpin) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

// Free
type SlotsFree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos      []int32 `protobuf:"varint,1,rep,packed,name=pos,proto3" json:"pos,omitempty"`    // free图标位置
	FreeSpin int32   `protobuf:"varint,2,opt,name=freeSpin,proto3" json:"freeSpin,omitempty"` // 奖励免费摇奖次数
}

func (x *SlotsFree) Reset() {
	*x = SlotsFree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotsFree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsFree) ProtoMessage() {}

func (x *SlotsFree) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsFree.ProtoReflect.Descriptor instead.
func (*SlotsFree) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{18}
}

func (x *SlotsFree) GetPos() []int32 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *SlotsFree) GetFreeSpin() int32 {
	if x != nil {
		return x.FreeSpin
	}
	return 0
}

// Bonus
type SlotsBonus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos   []int32 `protobuf:"varint,1,rep,packed,name=pos,proto3" json:"pos,omitempty"`     // bonus图标位置
	Board []int32 `protobuf:"varint,2,rep,packed,name=board,proto3" json:"board,omitempty"` // 界面
	Win   int64   `protobuf:"varint,4,opt,name=win,proto3" json:"win,omitempty"`            // 中奖额度
	Money int64   `protobuf:"varint,5,opt,name=money,proto3" json:"money,omitempty"`        // 金币
}

func (x *SlotsBonus) Reset() {
	*x = SlotsBonus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotsBonus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsBonus) ProtoMessage() {}

func (x *SlotsBonus) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsBonus.ProtoReflect.Descriptor instead.
func (*SlotsBonus) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{19}
}

func (x *SlotsBonus) GetPos() []int32 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *SlotsBonus) GetBoard() []int32 {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *SlotsBonus) GetWin() int64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *SlotsBonus) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

// 老虎机摇奖
type ResSlotsSpin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       int32       `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GameId    int32       `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Money     int64       `protobuf:"varint,3,opt,name=money,proto3" json:"money,omitempty"`                      // 金币
	Win       int64       `protobuf:"varint,4,opt,name=win,proto3" json:"win,omitempty"`                          // 赢钱
	Board     []int32     `protobuf:"varint,5,rep,packed,name=board,proto3" json:"board,omitempty"`               // 面板
	Lines     []int32     `protobuf:"varint,6,rep,packed,name=lines,proto3" json:"lines,omitempty"`               // 中奖线路
	Free      bool        `protobuf:"varint,7,opt,name=free,proto3" json:"free,omitempty"`                        // 中免费游戏
	FreeData  *SlotsFree  `protobuf:"bytes,8,opt,name=free_data,json=freeData,proto3" json:"free_data,omitempty"` // free数据
	Bonus     bool        `protobuf:"varint,9,opt,name=bonus,proto3" json:"bonus,omitempty"`
	BonusData *SlotsBonus `protobuf:"bytes,10,opt,name=bonus_data,json=bonusData,proto3" json:"bonus_data,omitempty"` // bonus数据
	LeftSpin  int32       `protobuf:"varint,11,opt,name=leftSpin,proto3" json:"leftSpin,omitempty"`                   // 剩余免费摇奖次数
}

func (x *ResSlotsSpin) Reset() {
	*x = ResSlotsSpin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResSlotsSpin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResSlotsSpin) ProtoMessage() {}

func (x *ResSlotsSpin) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResSlotsSpin.ProtoReflect.Descriptor instead.
func (*ResSlotsSpin) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{20}
}

func (x *ResSlotsSpin) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ResSlotsSpin) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *ResSlotsSpin) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *ResSlotsSpin) GetWin() int64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *ResSlotsSpin) GetBoard() []int32 {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *ResSlotsSpin) GetLines() []int32 {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *ResSlotsSpin) GetFree() bool {
	if x != nil {
		return x.Free
	}
	return false
}

func (x *ResSlotsSpin) GetFreeData() *SlotsFree {
	if x != nil {
		return x.FreeData
	}
	return nil
}

func (x *ResSlotsSpin) GetBonus() bool {
	if x != nil {
		return x.Bonus
	}
	return false
}

func (x *ResSlotsSpin) GetBonusData() *SlotsBonus {
	if x != nil {
		return x.BonusData
	}
	return nil
}

func (x *ResSlotsSpin) GetLeftSpin() int32 {
	if x != nil {
		return x.LeftSpin
	}
	return 0
}

// 玩家离开房间
type ReqLeaveRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateId uint32 `protobuf:"varint,1,opt,name=gateId,proto3" json:"gateId,omitempty"`
	RoomId uint32 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *ReqLeaveRoom) Reset() {
	*x = ReqLeaveRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLeaveRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLeaveRoom) ProtoMessage() {}

func (x *ReqLeaveRoom) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLeaveRoom.ProtoReflect.Descriptor instead.
func (*ReqLeaveRoom) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{21}
}

func (x *ReqLeaveRoom) GetGateId() uint32 {
	if x != nil {
		return x.GateId
	}
	return 0
}

func (x *ReqLeaveRoom) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 玩家离线
type Offline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Offline) Reset() {
	*x = Offline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Offline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offline) ProtoMessage() {}

func (x *Offline) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offline.ProtoReflect.Descriptor instead.
func (*Offline) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{22}
}

// 开始游戏
type StartGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId uint32   `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`      // 房间ID
	HallId uint32   `protobuf:"varint,2,opt,name=hallId,proto3" json:"hallId,omitempty"`      // 大厅ID
	Uids   []uint32 `protobuf:"varint,3,rep,packed,name=uids,proto3" json:"uids,omitempty"`   // 所有玩家的uid
	Gates  []uint32 `protobuf:"varint,4,rep,packed,name=gates,proto3" json:"gates,omitempty"` // 服务ID
	TempId uint32   `protobuf:"varint,5,opt,name=tempId,proto3" json:"tempId,omitempty"`      // 模板ID
}

func (x *StartGame) Reset() {
	*x = StartGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGame) ProtoMessage() {}

func (x *StartGame) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGame.ProtoReflect.Descriptor instead.
func (*StartGame) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{23}
}

func (x *StartGame) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *StartGame) GetHallId() uint32 {
	if x != nil {
		return x.HallId
	}
	return 0
}

func (x *StartGame) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *StartGame) GetGates() []uint32 {
	if x != nil {
		return x.Gates
	}
	return nil
}

func (x *StartGame) GetTempId() uint32 {
	if x != nil {
		return x.TempId
	}
	return 0
}

// 同步数据
type SyncData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	RoomId uint32 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	GameId uint32 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
}

func (x *SyncData) Reset() {
	*x = SyncData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncData) ProtoMessage() {}

func (x *SyncData) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncData.ProtoReflect.Descriptor instead.
func (*SyncData) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{24}
}

func (x *SyncData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *SyncData) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SyncData) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

// 完成数据
type Tap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`       // uid
	RoomId uint32 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"` // roomId
	Tap    int32  `protobuf:"varint,3,opt,name=tap,proto3" json:"tap,omitempty"`       // x坐标
	Tips   string `protobuf:"bytes,4,opt,name=tips,proto3" json:"tips,omitempty"`      // 提示
}

func (x *Tap) Reset() {
	*x = Tap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tap) ProtoMessage() {}

func (x *Tap) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tap.ProtoReflect.Descriptor instead.
func (*Tap) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{25}
}

func (x *Tap) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Tap) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Tap) GetTap() int32 {
	if x != nil {
		return x.Tap
	}
	return 0
}

func (x *Tap) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

// 空数据
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{26}
}

// 游戏结束
type GameOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`      // 游戏结束
	TempId uint32 `protobuf:"varint,2,opt,name=tempId,proto3" json:"tempId,omitempty"` // 房间模板ID
	RoomId uint32 `protobuf:"varint,3,opt,name=roomId,proto3" json:"roomId,omitempty"` // 房间ID
}

func (x *GameOver) Reset() {
	*x = GameOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOver) ProtoMessage() {}

func (x *GameOver) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOver.ProtoReflect.Descriptor instead.
func (*GameOver) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{27}
}

func (x *GameOver) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GameOver) GetTempId() uint32 {
	if x != nil {
		return x.TempId
	}
	return 0
}

func (x *GameOver) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 多播消息
type MultiMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids []uint32 `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	Data []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MultiMsg) Reset() {
	*x = MultiMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiMsg) ProtoMessage() {}

func (x *MultiMsg) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiMsg.ProtoReflect.Descriptor instead.
func (*MultiMsg) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{28}
}

func (x *MultiMsg) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *MultiMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 重连
type Reconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TempId uint32 `protobuf:"varint,1,opt,name=tempId,proto3" json:"tempId,omitempty"`
	RoomId uint32 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	HallId uint32 `protobuf:"varint,3,opt,name=hallId,proto3" json:"hallId,omitempty"`
	GateId uint32 `protobuf:"varint,4,opt,name=gateId,proto3" json:"gateId,omitempty"`
}

func (x *Reconnect) Reset() {
	*x = Reconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reconnect) ProtoMessage() {}

func (x *Reconnect) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reconnect.ProtoReflect.Descriptor instead.
func (*Reconnect) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{29}
}

func (x *Reconnect) GetTempId() uint32 {
	if x != nil {
		return x.TempId
	}
	return 0
}

func (x *Reconnect) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Reconnect) GetHallId() uint32 {
	if x != nil {
		return x.HallId
	}
	return 0
}

func (x *Reconnect) GetGateId() uint32 {
	if x != nil {
		return x.GateId
	}
	return 0
}

// 测试
type Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	StartTime int64  `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   int64  `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *Test) Reset() {
	*x = Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{30}
}

func (x *Test) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Test) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Test) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

var File_test_proto protoreflect.FileDescriptor

var file_test_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x0c,
	0x52, 0x65, 0x71, 0x47, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61,
	0x74, 0x65, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x47, 0x61, 0x74, 0x65, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x6c, 0x6c, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x0e,
	0x0a, 0x0c, 0x52, 0x65, 0x71, 0x47, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x22, 0x29,
	0x0a, 0x08, 0x47, 0x61, 0x74, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x47, 0x0a, 0x09, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x44, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65,
	0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0d, 0x0a, 0x0b, 0x52,
	0x65, 0x71, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x08, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x2e, 0x0a, 0x0b,
	0x52, 0x65, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x72,
	0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x2e, 0x0a, 0x0c,
	0x52, 0x65, 0x71, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1e, 0x0a, 0x0a,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x0c,
	0x52, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73,
	0x22, 0x29, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x49, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x09,
	0x53, 0x6c, 0x6f, 0x74, 0x73, 0x45, 0x6c, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x6c, 0x65,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x6c, 0x65, 0x6d,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6c, 0x65, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x33, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x34, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x35, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x35, 0x22, 0x3f, 0x0a, 0x09, 0x53, 0x6c, 0x6f, 0x74, 0x73,
	0x4c, 0x69, 0x6e, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x07, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x6f, 0x73, 0x22, 0xa7, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x6c, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x45, 0x6c, 0x65, 0x6d, 0x52, 0x05, 0x65,
	0x6c, 0x65, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x65, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x03, 0x62, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x20, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6e,
	0x65, 0x73, 0x22, 0x29, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x6c,
	0x6f, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x49, 0x64, 0x22, 0x76, 0x0a,
	0x0c, 0x52, 0x65, 0x71, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x53, 0x70, 0x69, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x65, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x62, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x09, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x46, 0x72,
	0x65, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x03, 0x70, 0x6f, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x65, 0x65, 0x53, 0x70, 0x69, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x72, 0x65, 0x65, 0x53, 0x70, 0x69, 0x6e,
	0x22, 0x5c, 0x0a, 0x0a, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6f, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x77, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x22, 0xa7,
	0x02, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x53, 0x70, 0x69, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x77, 0x69,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x72, 0x65, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x72, 0x65,
	0x65, 0x12, 0x27, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x46, 0x72, 0x65, 0x65,
	0x52, 0x08, 0x66, 0x72, 0x65, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f,
	0x6e, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x62, 0x6f, 0x6e, 0x75, 0x73,
	0x12, 0x2a, 0x0a, 0x0a, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x42, 0x6f, 0x6e, 0x75,
	0x73, 0x52, 0x09, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x65, 0x66, 0x74, 0x53, 0x70, 0x69, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x6c, 0x65, 0x66, 0x74, 0x53, 0x70, 0x69, 0x6e, 0x22, 0x3e, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x74, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x09, 0x0a, 0x07, 0x4f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x22, 0x7d, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x6c, 0x6c,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x61, 0x6c, 0x6c, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04,
	0x75, 0x69, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x05, 0x67, 0x61, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65,
	0x6d, 0x70, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x65, 0x6d, 0x70,
	0x49, 0x64, 0x22, 0x4e, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x22, 0x55, 0x0a, 0x03, 0x54, 0x61, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x74, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x4e, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6d, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x74, 0x65, 0x6d, 0x70, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x22, 0x32, 0x0a, 0x08, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4d, 0x73, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04, 0x75, 0x69,
	0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6b, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6d, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x65, 0x6d, 0x70, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67,
	0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x74,
	0x65, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x2a, 0x35, 0x0a, 0x08, 0x4b, 0x69, 0x63, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x71, 0x75, 0x65, 0x65, 0x7a, 0x65, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x61,
	0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x02, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData = file_test_proto_rawDesc
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_proto_rawDescData)
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_test_proto_goTypes = []interface{}{
	(KickType)(0),         // 0: KickType
	(*ReqGateLogin)(nil),  // 1: ReqGateLogin
	(*ResGateLogin)(nil),  // 2: ResGateLogin
	(*ReqGateLeave)(nil),  // 3: ReqGateLeave
	(*GateKick)(nil),      // 4: GateKick
	(*HeartBeat)(nil),     // 5: HeartBeat
	(*Regist)(nil),        // 6: Regist
	(*GatePushMsg)(nil),   // 7: GatePushMsg
	(*ReqRoomList)(nil),   // 8: ReqRoomList
	(*RoomInfo)(nil),      // 9: RoomInfo
	(*ResRoomList)(nil),   // 10: ResRoomList
	(*ReqEnterRoom)(nil),  // 11: ReqEnterRoom
	(*ResEnterRoom)(nil),  // 12: ResEnterRoom
	(*ReqEnterSlots)(nil), // 13: ReqEnterSlots
	(*SlotsElem)(nil),     // 14: SlotsElem
	(*SlotsLine)(nil),     // 15: SlotsLine
	(*ResEnterSlots)(nil), // 16: ResEnterSlots
	(*ReqLeaveSlots)(nil), // 17: ReqLeaveSlots
	(*ReqSlotsSpin)(nil),  // 18: ReqSlotsSpin
	(*SlotsFree)(nil),     // 19: SlotsFree
	(*SlotsBonus)(nil),    // 20: SlotsBonus
	(*ResSlotsSpin)(nil),  // 21: ResSlotsSpin
	(*ReqLeaveRoom)(nil),  // 22: ReqLeaveRoom
	(*Offline)(nil),       // 23: Offline
	(*StartGame)(nil),     // 24: StartGame
	(*SyncData)(nil),      // 25: SyncData
	(*Tap)(nil),           // 26: Tap
	(*Empty)(nil),         // 27: Empty
	(*GameOver)(nil),      // 28: GameOver
	(*MultiMsg)(nil),      // 29: MultiMsg
	(*Reconnect)(nil),     // 30: Reconnect
	(*Test)(nil),          // 31: Test
}
var file_test_proto_depIdxs = []int32{
	0,  // 0: GateKick.type:type_name -> KickType
	9,  // 1: ResRoomList.rooms:type_name -> RoomInfo
	14, // 2: ResEnterSlots.elems:type_name -> SlotsElem
	15, // 3: ResEnterSlots.lines:type_name -> SlotsLine
	19, // 4: ResSlotsSpin.free_data:type_name -> SlotsFree
	20, // 5: ResSlotsSpin.bonus_data:type_name -> SlotsBonus
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGateLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResGateLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGateLeave); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateKick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Regist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatePushMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqRoomList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResRoomList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqEnterRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResEnterRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqEnterSlots); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotsElem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotsLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResEnterSlots); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLeaveSlots); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSlotsSpin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotsFree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotsBonus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResSlotsSpin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLeaveRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Offline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_rawDesc = nil
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
