// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.0
// source: test.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录
type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	From     int32  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	GateId   uint32 `protobuf:"varint,3,opt,name=gateId,proto3" json:"gateId,omitempty"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *LoginReq) GetGateId() uint32 {
	if x != nil {
		return x.GateId
	}
	return 0
}

// 登录成功
type LoginRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	GameId   uint32 `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	RoomId   uint32 `protobuf:"varint,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	HallId   uint32 `protobuf:"varint,4,opt,name=hallId,proto3" json:"hallId,omitempty"`
	Nick     string `protobuf:"bytes,5,opt,name=nick,proto3" json:"nick,omitempty"`
	IconId   uint32 `protobuf:"varint,6,opt,name=iconId,proto3" json:"iconId,omitempty"`
	IsRegist bool   `protobuf:"varint,7,opt,name=isRegist,proto3" json:"isRegist,omitempty"`
	Uid      uint32 `protobuf:"varint,8,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *LoginRsp) Reset() {
	*x = LoginRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRsp) ProtoMessage() {}

func (x *LoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRsp.ProtoReflect.Descriptor instead.
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRsp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *LoginRsp) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *LoginRsp) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *LoginRsp) GetHallId() uint32 {
	if x != nil {
		return x.HallId
	}
	return 0
}

func (x *LoginRsp) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *LoginRsp) GetIconId() uint32 {
	if x != nil {
		return x.IconId
	}
	return 0
}

func (x *LoginRsp) GetIsRegist() bool {
	if x != nil {
		return x.IsRegist
	}
	return false
}

func (x *LoginRsp) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// 离开
type LogoutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

// 踢人
type GateKick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type KickType `protobuf:"varint,1,opt,name=type,proto3,enum=KickType" json:"type,omitempty"`
}

func (x *GateKick) Reset() {
	*x = GateKick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateKick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateKick) ProtoMessage() {}

func (x *GateKick) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateKick.ProtoReflect.Descriptor instead.
func (*GateKick) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *GateKick) GetType() KickType {
	if x != nil {
		return x.Type
	}
	return KickType_Unknow
}

// 心跳
type HeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerType uint32 `protobuf:"varint,1,opt,name=serverType,proto3" json:"serverType,omitempty"`
	ServerId   uint32 `protobuf:"varint,2,opt,name=serverId,proto3" json:"serverId,omitempty"`
}

func (x *HeartBeat) Reset() {
	*x = HeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeat) ProtoMessage() {}

func (x *HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeat.ProtoReflect.Descriptor instead.
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *HeartBeat) GetServerType() uint32 {
	if x != nil {
		return x.ServerType
	}
	return 0
}

func (x *HeartBeat) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

// 注册
type Regist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerType uint32 `protobuf:"varint,1,opt,name=serverType,proto3" json:"serverType,omitempty"`
	ServerId   uint32 `protobuf:"varint,2,opt,name=serverId,proto3" json:"serverId,omitempty"`
}

func (x *Regist) Reset() {
	*x = Regist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Regist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Regist) ProtoMessage() {}

func (x *Regist) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Regist.ProtoReflect.Descriptor instead.
func (*Regist) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *Regist) GetServerType() uint32 {
	if x != nil {
		return x.ServerType
	}
	return 0
}

func (x *Regist) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

// 推送
type GatePushMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GatePushMsg) Reset() {
	*x = GatePushMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatePushMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatePushMsg) ProtoMessage() {}

func (x *GatePushMsg) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatePushMsg.ProtoReflect.Descriptor instead.
func (*GatePushMsg) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (x *GatePushMsg) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// 请求游戏列表
type GetGameListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gids []int32 `protobuf:"varint,1,rep,packed,name=gids,proto3" json:"gids,omitempty"` // 游戏id len=0全部数据 len>0游戏数据
}

func (x *GetGameListReq) Reset() {
	*x = GetGameListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListReq) ProtoMessage() {}

func (x *GetGameListReq) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListReq.ProtoReflect.Descriptor instead.
func (*GetGameListReq) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *GetGameListReq) GetGids() []int32 {
	if x != nil {
		return x.Gids
	}
	return nil
}

// 房间信息
type GameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId    uint32     `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`                 // 游戏id
	Status    GameStatus `protobuf:"varint,2,opt,name=status,proto3,enum=GameStatus" json:"status,omitempty"` // 游戏状态
	StartTime uint32     `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`           // 开始时间
	EndTime   uint32     `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`               // 结束时间
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *GameInfo) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GameInfo) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_Custom
}

func (x *GameInfo) GetStartTime() uint32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GameInfo) GetEndTime() uint32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// 答复游戏列表
type GetGameListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Games []*GameInfo `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
}

func (x *GetGameListRsp) Reset() {
	*x = GetGameListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListRsp) ProtoMessage() {}

func (x *GetGameListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListRsp.ProtoReflect.Descriptor instead.
func (*GetGameListRsp) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{9}
}

func (x *GetGameListRsp) GetGames() []*GameInfo {
	if x != nil {
		return x.Games
	}
	return nil
}

// 请求房间列表
type GetRoomListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId uint32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
}

func (x *GetRoomListReq) Reset() {
	*x = GetRoomListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomListReq) ProtoMessage() {}

func (x *GetRoomListReq) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomListReq.ProtoReflect.Descriptor instead.
func (*GetRoomListReq) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{10}
}

func (x *GetRoomListReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

// 房间信息
type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint32 `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	RoomId   uint32 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Tag      uint32 `protobuf:"varint,3,opt,name=tag,proto3" json:"tag,omitempty"`       // 0正常房间 1热门房间 2推荐房间 3新的房间
	GameId   uint32 `protobuf:"varint,4,opt,name=gameId,proto3" json:"gameId,omitempty"` // 游戏id
	Info     string `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`      // 房间描述
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{11}
}

func (x *RoomInfo) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *RoomInfo) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomInfo) GetTag() uint32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *RoomInfo) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *RoomInfo) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

// 答复房间列表
type GetRoomListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*RoomInfo `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *GetRoomListRsp) Reset() {
	*x = GetRoomListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomListRsp) ProtoMessage() {}

func (x *GetRoomListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomListRsp.ProtoReflect.Descriptor instead.
func (*GetRoomListRsp) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{12}
}

func (x *GetRoomListRsp) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// 请求进入房间
type EnterRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId uint32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	RoomId uint32 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *EnterRoomReq) Reset() {
	*x = EnterRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterRoomReq) ProtoMessage() {}

func (x *EnterRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterRoomReq.ProtoReflect.Descriptor instead.
func (*EnterRoomReq) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{13}
}

func (x *EnterRoomReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *EnterRoomReq) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 进房答复
type EnterRoomRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids []uint32 `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
}

func (x *EnterRoomRsp) Reset() {
	*x = EnterRoomRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterRoomRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterRoomRsp) ProtoMessage() {}

func (x *EnterRoomRsp) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterRoomRsp.ProtoReflect.Descriptor instead.
func (*EnterRoomRsp) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{14}
}

func (x *EnterRoomRsp) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

// 进入老虎机
type EnterSlotsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
}

func (x *EnterSlotsReq) Reset() {
	*x = EnterSlotsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterSlotsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSlotsReq) ProtoMessage() {}

func (x *EnterSlotsReq) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSlotsReq.ProtoReflect.Descriptor instead.
func (*EnterSlotsReq) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{15}
}

func (x *EnterSlotsReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type SlotsElem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElemId   int32  `protobuf:"varint,1,opt,name=elem_id,json=elemId,proto3" json:"elem_id,omitempty"`      // 元素id
	ElemName string `protobuf:"bytes,2,opt,name=elem_name,json=elemName,proto3" json:"elem_name,omitempty"` // 元素名称
	Multi3   int32  `protobuf:"varint,3,opt,name=multi3,proto3" json:"multi3,omitempty"`                    // 3个元素倍数
	Multi4   int32  `protobuf:"varint,4,opt,name=multi4,proto3" json:"multi4,omitempty"`                    // 4个元素倍数
	Multi5   int32  `protobuf:"varint,5,opt,name=multi5,proto3" json:"multi5,omitempty"`                    // 5个元素倍数
}

func (x *SlotsElem) Reset() {
	*x = SlotsElem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotsElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsElem) ProtoMessage() {}

func (x *SlotsElem) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsElem.ProtoReflect.Descriptor instead.
func (*SlotsElem) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{16}
}

func (x *SlotsElem) GetElemId() int32 {
	if x != nil {
		return x.ElemId
	}
	return 0
}

func (x *SlotsElem) GetElemName() string {
	if x != nil {
		return x.ElemName
	}
	return ""
}

func (x *SlotsElem) GetMulti3() int32 {
	if x != nil {
		return x.Multi3
	}
	return 0
}

func (x *SlotsElem) GetMulti4() int32 {
	if x != nil {
		return x.Multi4
	}
	return 0
}

func (x *SlotsElem) GetMulti5() int32 {
	if x != nil {
		return x.Multi5
	}
	return 0
}

type SlotsLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LineId  int32   `protobuf:"varint,1,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	LinePos []int32 `protobuf:"varint,2,rep,packed,name=line_pos,json=linePos,proto3" json:"line_pos,omitempty"`
}

func (x *SlotsLine) Reset() {
	*x = SlotsLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotsLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsLine) ProtoMessage() {}

func (x *SlotsLine) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsLine.ProtoReflect.Descriptor instead.
func (*SlotsLine) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{17}
}

func (x *SlotsLine) GetLineId() int32 {
	if x != nil {
		return x.LineId
	}
	return 0
}

func (x *SlotsLine) GetLinePos() []int32 {
	if x != nil {
		return x.LinePos
	}
	return nil
}

type EnterSlotsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int32        `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	Elems  []*SlotsElem `protobuf:"bytes,2,rep,name=elems,proto3" json:"elems,omitempty"`         // 元素
	Bet    []int32      `protobuf:"varint,3,rep,packed,name=bet,proto3" json:"bet,omitempty"`     // 下注额
	Level  []int32      `protobuf:"varint,4,rep,packed,name=level,proto3" json:"level,omitempty"` // 下注等级
	Line   []int32      `protobuf:"varint,5,rep,packed,name=line,proto3" json:"line,omitempty"`   // 下注线
	Lines  []*SlotsLine `protobuf:"bytes,6,rep,name=lines,proto3" json:"lines,omitempty"`         // 中奖线路
}

func (x *EnterSlotsRsp) Reset() {
	*x = EnterSlotsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterSlotsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSlotsRsp) ProtoMessage() {}

func (x *EnterSlotsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSlotsRsp.ProtoReflect.Descriptor instead.
func (*EnterSlotsRsp) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{18}
}

func (x *EnterSlotsRsp) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *EnterSlotsRsp) GetElems() []*SlotsElem {
	if x != nil {
		return x.Elems
	}
	return nil
}

func (x *EnterSlotsRsp) GetBet() []int32 {
	if x != nil {
		return x.Bet
	}
	return nil
}

func (x *EnterSlotsRsp) GetLevel() []int32 {
	if x != nil {
		return x.Level
	}
	return nil
}

func (x *EnterSlotsRsp) GetLine() []int32 {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *EnterSlotsRsp) GetLines() []*SlotsLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

// 离开老虎机
type LeaveSlotsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotsId int32 `protobuf:"varint,1,opt,name=slotsId,proto3" json:"slotsId,omitempty"`
}

func (x *LeaveSlotsReq) Reset() {
	*x = LeaveSlotsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveSlotsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSlotsReq) ProtoMessage() {}

func (x *LeaveSlotsReq) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSlotsReq.ProtoReflect.Descriptor instead.
func (*LeaveSlotsReq) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{19}
}

func (x *LeaveSlotsReq) GetSlotsId() int32 {
	if x != nil {
		return x.SlotsId
	}
	return 0
}

// 老虎机摇奖
type SlotsSpinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GameId int32 `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Bet    int32 `protobuf:"varint,3,opt,name=bet,proto3" json:"bet,omitempty"`     // 下注
	Level  int32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"` // 级别
	Lines  int32 `protobuf:"varint,5,opt,name=lines,proto3" json:"lines,omitempty"` // 线数
}

func (x *SlotsSpinReq) Reset() {
	*x = SlotsSpinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotsSpinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsSpinReq) ProtoMessage() {}

func (x *SlotsSpinReq) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsSpinReq.ProtoReflect.Descriptor instead.
func (*SlotsSpinReq) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{20}
}

func (x *SlotsSpinReq) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SlotsSpinReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *SlotsSpinReq) GetBet() int32 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *SlotsSpinReq) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SlotsSpinReq) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

// Free
type SlotsFree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos      []int32 `protobuf:"varint,1,rep,packed,name=pos,proto3" json:"pos,omitempty"`    // free图标位置
	FreeSpin int32   `protobuf:"varint,2,opt,name=freeSpin,proto3" json:"freeSpin,omitempty"` // 奖励免费摇奖次数
}

func (x *SlotsFree) Reset() {
	*x = SlotsFree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotsFree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsFree) ProtoMessage() {}

func (x *SlotsFree) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsFree.ProtoReflect.Descriptor instead.
func (*SlotsFree) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{21}
}

func (x *SlotsFree) GetPos() []int32 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *SlotsFree) GetFreeSpin() int32 {
	if x != nil {
		return x.FreeSpin
	}
	return 0
}

// Bonus
type SlotsBonus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos   []int32 `protobuf:"varint,1,rep,packed,name=pos,proto3" json:"pos,omitempty"`     // bonus图标位置
	Board []int32 `protobuf:"varint,2,rep,packed,name=board,proto3" json:"board,omitempty"` // 界面
	Win   int64   `protobuf:"varint,3,opt,name=win,proto3" json:"win,omitempty"`            // 中奖额度
	Money int64   `protobuf:"varint,4,opt,name=money,proto3" json:"money,omitempty"`        // 金币
}

func (x *SlotsBonus) Reset() {
	*x = SlotsBonus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotsBonus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsBonus) ProtoMessage() {}

func (x *SlotsBonus) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsBonus.ProtoReflect.Descriptor instead.
func (*SlotsBonus) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{22}
}

func (x *SlotsBonus) GetPos() []int32 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *SlotsBonus) GetBoard() []int32 {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *SlotsBonus) GetWin() int64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *SlotsBonus) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

// 老虎机摇奖
type SlotsSpinRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       int32       `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GameId    int32       `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Money     int64       `protobuf:"varint,3,opt,name=money,proto3" json:"money,omitempty"`                      // 金币
	Win       int64       `protobuf:"varint,4,opt,name=win,proto3" json:"win,omitempty"`                          // 赢钱
	Board     []int32     `protobuf:"varint,5,rep,packed,name=board,proto3" json:"board,omitempty"`               // 面板
	Lines     []int32     `protobuf:"varint,6,rep,packed,name=lines,proto3" json:"lines,omitempty"`               // 中奖线路
	Free      bool        `protobuf:"varint,7,opt,name=free,proto3" json:"free,omitempty"`                        // 中免费游戏
	FreeData  *SlotsFree  `protobuf:"bytes,8,opt,name=free_data,json=freeData,proto3" json:"free_data,omitempty"` // free数据
	Bonus     bool        `protobuf:"varint,9,opt,name=bonus,proto3" json:"bonus,omitempty"`
	BonusData *SlotsBonus `protobuf:"bytes,10,opt,name=bonus_data,json=bonusData,proto3" json:"bonus_data,omitempty"` // bonus数据
	LeftSpin  int32       `protobuf:"varint,11,opt,name=leftSpin,proto3" json:"leftSpin,omitempty"`                   // 剩余免费摇奖次数
	Bet       int64       `protobuf:"varint,12,opt,name=bet,proto3" json:"bet,omitempty"`                             // 下注
}

func (x *SlotsSpinRsp) Reset() {
	*x = SlotsSpinRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotsSpinRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotsSpinRsp) ProtoMessage() {}

func (x *SlotsSpinRsp) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotsSpinRsp.ProtoReflect.Descriptor instead.
func (*SlotsSpinRsp) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{23}
}

func (x *SlotsSpinRsp) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SlotsSpinRsp) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *SlotsSpinRsp) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *SlotsSpinRsp) GetWin() int64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *SlotsSpinRsp) GetBoard() []int32 {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *SlotsSpinRsp) GetLines() []int32 {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *SlotsSpinRsp) GetFree() bool {
	if x != nil {
		return x.Free
	}
	return false
}

func (x *SlotsSpinRsp) GetFreeData() *SlotsFree {
	if x != nil {
		return x.FreeData
	}
	return nil
}

func (x *SlotsSpinRsp) GetBonus() bool {
	if x != nil {
		return x.Bonus
	}
	return false
}

func (x *SlotsSpinRsp) GetBonusData() *SlotsBonus {
	if x != nil {
		return x.BonusData
	}
	return nil
}

func (x *SlotsSpinRsp) GetLeftSpin() int32 {
	if x != nil {
		return x.LeftSpin
	}
	return 0
}

func (x *SlotsSpinRsp) GetBet() int64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

// 玩家离开房间
type LeaveRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateId uint32 `protobuf:"varint,1,opt,name=gateId,proto3" json:"gateId,omitempty"`
	RoomId uint32 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *LeaveRoomReq) Reset() {
	*x = LeaveRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomReq) ProtoMessage() {}

func (x *LeaveRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomReq.ProtoReflect.Descriptor instead.
func (*LeaveRoomReq) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{24}
}

func (x *LeaveRoomReq) GetGateId() uint32 {
	if x != nil {
		return x.GateId
	}
	return 0
}

func (x *LeaveRoomReq) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 玩家离线
type Offline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Offline) Reset() {
	*x = Offline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Offline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offline) ProtoMessage() {}

func (x *Offline) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offline.ProtoReflect.Descriptor instead.
func (*Offline) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{25}
}

// 开始游戏
type StartGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId uint32   `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`    // 房间ID
	HallId uint32   `protobuf:"varint,2,opt,name=hallId,proto3" json:"hallId,omitempty"`    // 大厅ID
	Uids   []uint32 `protobuf:"varint,3,rep,packed,name=uids,proto3" json:"uids,omitempty"` // 所有玩家的uid
	TempId uint32   `protobuf:"varint,4,opt,name=tempId,proto3" json:"tempId,omitempty"`    // 模板ID
}

func (x *StartGame) Reset() {
	*x = StartGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGame) ProtoMessage() {}

func (x *StartGame) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGame.ProtoReflect.Descriptor instead.
func (*StartGame) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{26}
}

func (x *StartGame) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *StartGame) GetHallId() uint32 {
	if x != nil {
		return x.HallId
	}
	return 0
}

func (x *StartGame) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *StartGame) GetTempId() uint32 {
	if x != nil {
		return x.TempId
	}
	return 0
}

// 同步数据
type SyncData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	RoomId uint32 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	GameId uint32 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
}

func (x *SyncData) Reset() {
	*x = SyncData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncData) ProtoMessage() {}

func (x *SyncData) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncData.ProtoReflect.Descriptor instead.
func (*SyncData) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{27}
}

func (x *SyncData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *SyncData) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SyncData) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

// 麻将
type DeskMj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`              // 下标
	Uid   uint32 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                  // 玩家uid
	MjVal int32  `protobuf:"varint,3,opt,name=mj_val,json=mjVal,proto3" json:"mj_val,omitempty"` // 麻将值
}

func (x *DeskMj) Reset() {
	*x = DeskMj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeskMj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeskMj) ProtoMessage() {}

func (x *DeskMj) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeskMj.ProtoReflect.Descriptor instead.
func (*DeskMj) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{28}
}

func (x *DeskMj) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DeskMj) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DeskMj) GetMjVal() int32 {
	if x != nil {
		return x.MjVal
	}
	return 0
}

// 手牌
type FaMj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fapai  []*DeskMj `protobuf:"bytes,1,rep,name=fapai,proto3" json:"fapai,omitempty"`               // 发牌
	Pizi   *DeskMj   `protobuf:"bytes,2,opt,name=pizi,proto3" json:"pizi,omitempty"`                 // 皮子
	Touzi  []int32   `protobuf:"varint,3,rep,packed,name=touzi,proto3" json:"touzi,omitempty"`       // 骰子
	Zhuang uint32    `protobuf:"varint,4,opt,name=zhuang,proto3" json:"zhuang,omitempty"`            // 庄家
	Laizi  int32     `protobuf:"varint,5,opt,name=laizi,proto3" json:"laizi,omitempty"`              // 赖子
	CanOp  int32     `protobuf:"varint,7,opt,name=can_op,json=canOp,proto3" json:"can_op,omitempty"` // 庄家可执行操作
}

func (x *FaMj) Reset() {
	*x = FaMj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FaMj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaMj) ProtoMessage() {}

func (x *FaMj) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaMj.ProtoReflect.Descriptor instead.
func (*FaMj) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{29}
}

func (x *FaMj) GetFapai() []*DeskMj {
	if x != nil {
		return x.Fapai
	}
	return nil
}

func (x *FaMj) GetPizi() *DeskMj {
	if x != nil {
		return x.Pizi
	}
	return nil
}

func (x *FaMj) GetTouzi() []int32 {
	if x != nil {
		return x.Touzi
	}
	return nil
}

func (x *FaMj) GetZhuang() uint32 {
	if x != nil {
		return x.Zhuang
	}
	return 0
}

func (x *FaMj) GetLaizi() int32 {
	if x != nil {
		return x.Laizi
	}
	return 0
}

func (x *FaMj) GetCanOp() int32 {
	if x != nil {
		return x.CanOp
	}
	return 0
}

// 完成数据
type Tap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                  // uid
	RoomId uint32 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`            // roomId
	Tap    int32  `protobuf:"varint,3,opt,name=tap,proto3" json:"tap,omitempty"`                  // x坐标
	CanOp  int32  `protobuf:"varint,4,opt,name=can_op,json=canOp,proto3" json:"can_op,omitempty"` // 可操作
}

func (x *Tap) Reset() {
	*x = Tap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tap) ProtoMessage() {}

func (x *Tap) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tap.ProtoReflect.Descriptor instead.
func (*Tap) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{30}
}

func (x *Tap) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Tap) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Tap) GetTap() int32 {
	if x != nil {
		return x.Tap
	}
	return 0
}

func (x *Tap) GetCanOp() int32 {
	if x != nil {
		return x.CanOp
	}
	return 0
}

// 执行操作
type MjOpt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                  // uid
	RoomId uint32 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`            // roomId
	Op     int32  `protobuf:"varint,3,opt,name=op,proto3" json:"op,omitempty"`                    // 操作
	Mj     int32  `protobuf:"varint,4,opt,name=mj,proto3" json:"mj,omitempty"`                    // 麻将
	CanOp  int32  `protobuf:"varint,5,opt,name=can_op,json=canOp,proto3" json:"can_op,omitempty"` // 可操作
}

func (x *MjOpt) Reset() {
	*x = MjOpt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MjOpt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MjOpt) ProtoMessage() {}

func (x *MjOpt) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MjOpt.ProtoReflect.Descriptor instead.
func (*MjOpt) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{31}
}

func (x *MjOpt) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MjOpt) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *MjOpt) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *MjOpt) GetMj() int32 {
	if x != nil {
		return x.Mj
	}
	return 0
}

func (x *MjOpt) GetCanOp() int32 {
	if x != nil {
		return x.CanOp
	}
	return 0
}

// 空数据
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{32}
}

type GameOverUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`            // 玩家id
	Win    int64   `protobuf:"varint,2,opt,name=win,proto3" json:"win,omitempty"`            // 赢钱
	Hands  []int32 `protobuf:"varint,3,rep,packed,name=hands,proto3" json:"hands,omitempty"` // 手牌
	HuType int32   `protobuf:"varint,4,opt,name=huType,proto3" json:"huType,omitempty"`      // 胡类型
}

func (x *GameOverUser) Reset() {
	*x = GameOverUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameOverUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOverUser) ProtoMessage() {}

func (x *GameOverUser) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOverUser.ProtoReflect.Descriptor instead.
func (*GameOverUser) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{33}
}

func (x *GameOverUser) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GameOverUser) GetWin() int64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *GameOverUser) GetHands() []int32 {
	if x != nil {
		return x.Hands
	}
	return nil
}

func (x *GameOverUser) GetHuType() int32 {
	if x != nil {
		return x.HuType
	}
	return 0
}

// 游戏结束
type GameOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   string          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`      // 游戏结束
	TempId uint32          `protobuf:"varint,2,opt,name=tempId,proto3" json:"tempId,omitempty"` // 房间模板ID
	RoomId uint32          `protobuf:"varint,3,opt,name=roomId,proto3" json:"roomId,omitempty"` // 房间ID
	Users  []*GameOverUser `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`    // 玩家
}

func (x *GameOver) Reset() {
	*x = GameOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOver) ProtoMessage() {}

func (x *GameOver) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOver.ProtoReflect.Descriptor instead.
func (*GameOver) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{34}
}

func (x *GameOver) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GameOver) GetTempId() uint32 {
	if x != nil {
		return x.TempId
	}
	return 0
}

func (x *GameOver) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GameOver) GetUsers() []*GameOverUser {
	if x != nil {
		return x.Users
	}
	return nil
}

// 多播消息
type MultiBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids []uint32 `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	Data []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MultiBroadcast) Reset() {
	*x = MultiBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiBroadcast) ProtoMessage() {}

func (x *MultiBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiBroadcast.ProtoReflect.Descriptor instead.
func (*MultiBroadcast) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{35}
}

func (x *MultiBroadcast) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *MultiBroadcast) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 重连
type Reconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TempId uint32 `protobuf:"varint,1,opt,name=tempId,proto3" json:"tempId,omitempty"`
	RoomId uint32 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	HallId uint32 `protobuf:"varint,3,opt,name=hallId,proto3" json:"hallId,omitempty"`
	GateId uint32 `protobuf:"varint,4,opt,name=gateId,proto3" json:"gateId,omitempty"`
}

func (x *Reconnect) Reset() {
	*x = Reconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reconnect) ProtoMessage() {}

func (x *Reconnect) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reconnect.ProtoReflect.Descriptor instead.
func (*Reconnect) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{36}
}

func (x *Reconnect) GetTempId() uint32 {
	if x != nil {
		return x.TempId
	}
	return 0
}

func (x *Reconnect) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Reconnect) GetHallId() uint32 {
	if x != nil {
		return x.HallId
	}
	return 0
}

func (x *Reconnect) GetGateId() uint32 {
	if x != nil {
		return x.GateId
	}
	return 0
}

// 测试
type Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	StartTime int64  `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   int64  `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *Test) Reset() {
	*x = Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{37}
}

func (x *Test) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Test) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Test) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// 通用回复
type CommonRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=ErrorCode" json:"code,omitempty"`
}

func (x *CommonRsp) Reset() {
	*x = CommonRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRsp) ProtoMessage() {}

func (x *CommonRsp) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRsp.ProtoReflect.Descriptor instead.
func (*CommonRsp) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{38}
}

func (x *CommonRsp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_Success
}

var File_test_proto protoreflect.FileDescriptor

var file_test_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x65, 0x6e,
	0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x74, 0x65, 0x49, 0x64, 0x22, 0xbe, 0x01, 0x0a,
	0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x61, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x61, 0x6c,
	0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x63, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x0b, 0x0a,
	0x09, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x22, 0x29, 0x0a, 0x08, 0x47, 0x61,
	0x74, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x47, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65,
	0x61, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x44,
	0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65, 0x50, 0x75, 0x73, 0x68,
	0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x24, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x67, 0x69, 0x64, 0x73, 0x22, 0x7f, 0x0a,
	0x08, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x12, 0x23, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0b, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x31,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70,
	0x12, 0x1f, 0x0a, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x67, 0x61, 0x6d, 0x65,
	0x73, 0x22, 0x28, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x7c, 0x0a, 0x08, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x31, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x05, 0x72,
	0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x3e, 0x0a, 0x0c,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x0c,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73,
	0x22, 0x27, 0x0a, 0x0d, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x09, 0x53, 0x6c,
	0x6f, 0x74, 0x73, 0x45, 0x6c, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x6c, 0x65, 0x6d, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6c, 0x65, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x33, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x34, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x34, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x35, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x35, 0x22, 0x3f, 0x0a, 0x09, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x4c, 0x69,
	0x6e, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6c,
	0x69, 0x6e, 0x65, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x6c,
	0x69, 0x6e, 0x65, 0x50, 0x6f, 0x73, 0x22, 0xa7, 0x01, 0x0a, 0x0d, 0x45, 0x6e, 0x74, 0x65, 0x72,
	0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x05, 0x65, 0x6c, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x45, 0x6c, 0x65, 0x6d, 0x52, 0x05, 0x65, 0x6c, 0x65,
	0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x65, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x03, 0x62, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69,
	0x6e, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x20,
	0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x53, 0x6c, 0x6f, 0x74, 0x73, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73,
	0x22, 0x29, 0x0a, 0x0d, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x49, 0x64, 0x22, 0x76, 0x0a, 0x0c, 0x53,
	0x6c, 0x6f, 0x74, 0x73, 0x53, 0x70, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x62, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69,
	0x6e, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x09, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x46, 0x72, 0x65, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x70,
	0x6f, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x65, 0x65, 0x53, 0x70, 0x69, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x72, 0x65, 0x65, 0x53, 0x70, 0x69, 0x6e, 0x22, 0x5c,
	0x0a, 0x0a, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x77, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x22, 0xb9, 0x02, 0x0a,
	0x0c, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x53, 0x70, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x77, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x77, 0x69, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x72, 0x65, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x72, 0x65, 0x65, 0x12,
	0x27, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x46, 0x72, 0x65, 0x65, 0x52, 0x08,
	0x66, 0x72, 0x65, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x6e, 0x75,
	0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x12, 0x2a,
	0x0a, 0x0a, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x52,
	0x09, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x65,
	0x66, 0x74, 0x53, 0x70, 0x69, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x65,
	0x66, 0x74, 0x53, 0x70, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x65, 0x74, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x62, 0x65, 0x74, 0x22, 0x3e, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x76,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x74, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x09, 0x0a, 0x07, 0x4f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x22, 0x67, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x6c, 0x6c,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x61, 0x6c, 0x6c, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04,
	0x75, 0x69, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6d, 0x70, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x65, 0x6d, 0x70, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x08,
	0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x06,
	0x44, 0x65, 0x73, 0x6b, 0x4d, 0x6a, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x15,
	0x0a, 0x06, 0x6d, 0x6a, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6d, 0x6a, 0x56, 0x61, 0x6c, 0x22, 0x9d, 0x01, 0x0a, 0x04, 0x46, 0x61, 0x4d, 0x6a, 0x12, 0x1d,
	0x0a, 0x05, 0x66, 0x61, 0x70, 0x61, 0x69, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x44, 0x65, 0x73, 0x6b, 0x4d, 0x6a, 0x52, 0x05, 0x66, 0x61, 0x70, 0x61, 0x69, 0x12, 0x1b, 0x0a,
	0x04, 0x70, 0x69, 0x7a, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x44, 0x65,
	0x73, 0x6b, 0x4d, 0x6a, 0x52, 0x04, 0x70, 0x69, 0x7a, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x75, 0x7a, 0x69, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x75, 0x7a, 0x69,
	0x12, 0x16, 0x0a, 0x06, 0x7a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x7a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x69, 0x7a,
	0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x61, 0x69, 0x7a, 0x69, 0x12, 0x15,
	0x0a, 0x06, 0x63, 0x61, 0x6e, 0x5f, 0x6f, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x61, 0x6e, 0x4f, 0x70, 0x22, 0x58, 0x0a, 0x03, 0x54, 0x61, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x61, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x61, 0x6e, 0x5f,
	0x6f, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x61, 0x6e, 0x4f, 0x70, 0x22,
	0x68, 0x0a, 0x05, 0x4d, 0x6a, 0x4f, 0x70, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x6f, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6d, 0x6a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x6d, 0x6a, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x61, 0x6e, 0x5f, 0x6f, 0x70, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x63, 0x61, 0x6e, 0x4f, 0x70, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x60, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x77, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x75, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x75,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x73, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6d, 0x70, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x65, 0x6d, 0x70, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x38, 0x0a, 0x0e, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x6b, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6d, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x74, 0x65, 0x6d, 0x70, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x68, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x74, 0x65,
	0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x22, 0x50, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x12,
	0x1e, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData = file_test_proto_rawDesc
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_proto_rawDescData)
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_test_proto_goTypes = []interface{}{
	(*LoginReq)(nil),       // 0: LoginReq
	(*LoginRsp)(nil),       // 1: LoginRsp
	(*LogoutReq)(nil),      // 2: LogoutReq
	(*GateKick)(nil),       // 3: GateKick
	(*HeartBeat)(nil),      // 4: HeartBeat
	(*Regist)(nil),         // 5: Regist
	(*GatePushMsg)(nil),    // 6: GatePushMsg
	(*GetGameListReq)(nil), // 7: GetGameListReq
	(*GameInfo)(nil),       // 8: GameInfo
	(*GetGameListRsp)(nil), // 9: GetGameListRsp
	(*GetRoomListReq)(nil), // 10: GetRoomListReq
	(*RoomInfo)(nil),       // 11: RoomInfo
	(*GetRoomListRsp)(nil), // 12: GetRoomListRsp
	(*EnterRoomReq)(nil),   // 13: EnterRoomReq
	(*EnterRoomRsp)(nil),   // 14: EnterRoomRsp
	(*EnterSlotsReq)(nil),  // 15: EnterSlotsReq
	(*SlotsElem)(nil),      // 16: SlotsElem
	(*SlotsLine)(nil),      // 17: SlotsLine
	(*EnterSlotsRsp)(nil),  // 18: EnterSlotsRsp
	(*LeaveSlotsReq)(nil),  // 19: LeaveSlotsReq
	(*SlotsSpinReq)(nil),   // 20: SlotsSpinReq
	(*SlotsFree)(nil),      // 21: SlotsFree
	(*SlotsBonus)(nil),     // 22: SlotsBonus
	(*SlotsSpinRsp)(nil),   // 23: SlotsSpinRsp
	(*LeaveRoomReq)(nil),   // 24: LeaveRoomReq
	(*Offline)(nil),        // 25: Offline
	(*StartGame)(nil),      // 26: StartGame
	(*SyncData)(nil),       // 27: SyncData
	(*DeskMj)(nil),         // 28: DeskMj
	(*FaMj)(nil),           // 29: FaMj
	(*Tap)(nil),            // 30: Tap
	(*MjOpt)(nil),          // 31: MjOpt
	(*Empty)(nil),          // 32: Empty
	(*GameOverUser)(nil),   // 33: GameOverUser
	(*GameOver)(nil),       // 34: GameOver
	(*MultiBroadcast)(nil), // 35: MultiBroadcast
	(*Reconnect)(nil),      // 36: Reconnect
	(*Test)(nil),           // 37: Test
	(*CommonRsp)(nil),      // 38: CommonRsp
	(KickType)(0),          // 39: KickType
	(GameStatus)(0),        // 40: GameStatus
	(ErrorCode)(0),         // 41: ErrorCode
}
var file_test_proto_depIdxs = []int32{
	39, // 0: GateKick.type:type_name -> KickType
	40, // 1: GameInfo.status:type_name -> GameStatus
	8,  // 2: GetGameListRsp.games:type_name -> GameInfo
	11, // 3: GetRoomListRsp.rooms:type_name -> RoomInfo
	16, // 4: EnterSlotsRsp.elems:type_name -> SlotsElem
	17, // 5: EnterSlotsRsp.lines:type_name -> SlotsLine
	21, // 6: SlotsSpinRsp.free_data:type_name -> SlotsFree
	22, // 7: SlotsSpinRsp.bonus_data:type_name -> SlotsBonus
	28, // 8: FaMj.fapai:type_name -> DeskMj
	28, // 9: FaMj.pizi:type_name -> DeskMj
	33, // 10: GameOver.users:type_name -> GameOverUser
	41, // 11: CommonRsp.code:type_name -> ErrorCode
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	file_enum_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateKick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Regist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatePushMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterRoomRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterSlotsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotsElem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotsLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterSlotsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveSlotsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotsSpinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotsFree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotsBonus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotsSpinRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Offline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeskMj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FaMj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MjOpt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameOverUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[37].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[38].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_rawDesc = nil
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
